### ISSUE TITLE
USB CTYPE power supply value for Rog Z13

### ISSUE THREAD

**Issue by mckim0306** [osy/XG_Mobile_Station#16]
Hello, I'm currently waiting to place an order for JLCPCB and I'd like to ask you because I have a question.
It has been changed from v0.5.1 to 100W -> 65W based on the latest release,
Is Turbo Mode supported on the Rog Flow series?
If not, should I proceed with the change in the hardware?
Or is it a software-controlled part?

**Comment by osy** [comment]
if you're building the lite version that change doesn't apply because the lite version doesn't have any active usb component, it just passes through the usb port. If you're building the full board, you can still configure the TI PD to 100W (20V 5A) and it will work. However, the reason why I lowered it to 65W is because the XG Station Pro power supply is 330W so if you allocate 100W to the charger, you only have 230W left for the GPU meaning you can't use some of the higher end cards. On the Ally, 65W is all that's needed for turbo mode and therefore I lowered it to that.
